[Onboard] add new sample of Office Add-in
OfficeDev/teams-toolkit-samples pull request #1372
Opened 2024-12-06 06:56 UTC by hermanwenhe

2024-12-11 07:10 UTC, MingjiaLiu1995 requested changes

2024-12-11 07:10 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +### Deploy and publish
```suggestion

```

2024-12-11 07:10 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +Currently unified manifest of Office add-in is in public preview, so it does not support deploy and publish.
```suggestion

```

2024-12-11 07:10 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +   ![Visual Studio Code debug configuration for Office](./assets/launch.png)
```suggestion

```
Seems the image does not exist

2024-12-11 07:10 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +Currently unified manifest of Office add-in is in public preview, so it does not support deploy and publish.
put this at front

2024-12-11 07:20 UTC, MingjiaLiu1995 commented
Hi @summzhan , do we have a content review process for adding new samples to Teams Toolkit? Should we reach out to some reviewers or should we ensure the content ourselves? Thanks!

2024-12-12 09:33 UTC, MingjiaLiu1995 approved these changes

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +   Once the Office app is open, you can select the ribbon command to show the add-in task pane. The snapshot shows Excel as an example, and the other Office applications share the same behavior.
```suggestion
   Once the Office app is open, you can select the ribbon command to show the add-in task pane. 
```

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +   The taskpane opens and you can check the sideloaded add-in.
```suggestion
- The taskpane opens and you can check the sideloaded add-in.
```

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +   ![Excel add-in show taskpane](./assets/excel-ribbon.png)
Same comment here

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +   ![Excel add-in task pane opened](./assets/thumbnail.png)
Same here

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +Now you have the ability to create a single unit of distribution for all your Office applications by using the same manifest format and schema, based on the current JSON-formatted MetaOS manifest.
With the unified app manifest, you can create a single unit of distribution for all your Microsoft 365 extensions by using the same manifest format and schema.

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +
```suggestion
```

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +- How to create an Office add-ins with a unified manifest that works on Word, Excel, Powerpoint, and Outlook.
```suggestion
- How to create an Office add-in with a unified manifest that works on Word, Excel, Powerpoint, and Outlook. 
```

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +You can find the app manifest in `./appPackage` folder. The folder contains one manifest file:
```suggestion
You can find the app manifest in `./appPackage` folder. The folder contains the manifest file `manifest.json` for Office add-in running locally.
```

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +- `manifest.json`: Manifest file for Office add-in running locally.
```suggestion

```

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +
```suggestion
```

2024-12-12 09:33 UTC, MingjiaLiu1995 commented on hello-world-office-addin/README.md
> +
```suggestion
```

2024-12-16 02:46 UTC, tecton approved these changes

2024-12-16 02:47 UTC, merged